name: dirbbox
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  font_awesome_flutter: 10.1.0
  local_auth: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/logo.png
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

